- hosts: all
  become: true
  tasks:
    - name: install ha proxy
      yum:
         name: httpd
         state: installed
        
    - name: add index
      copy:
         content: This is my First copy
         dest: /var/www/html/index.html
           
    - name: start service
      service:
           name: httpd
           state: started
           enabled: yes
